language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "infnet_avaliacao"
    token:
      secure: "557b9f65e299ebd89119367f3e08410e52a2cb4d"
jdk:
 - oraclejdk8
script:
# - mvn clean install test jacoco:report coveralls:report
 - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email:
    recipients:
      - marcosjava2008@gmail.com