CREATE TABLE usuario(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  login VARCHAR(50) NOT NULL,
  senha VARCHAR(200) NOT NULL,
  perfil VARCHAR(3) NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT un_login UNIQUE (login);