CREATE TABLE aluno(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(120) NOT NULL,
  cpf INTEGER(11) UNIQUE NOT NULL,
  nome varchar(100) NOT NULL
);
ALTER TABLE aluno ADD CONSTRAINT pk_id_aluno PRIMARY KEY (id);