INSERT INTO role(nome) VALUES('LISTAR_USUARIO');
INSERT INTO role(nome) VALUES('CADASTRAR_USUARIO');
INSERT INTO role(nome) VALUES('ALTERAR_USUARIO');
INSERT INTO role(nome) VALUES('DETALHAR_USUARIO');
INSERT INTO role(nome) VALUES('REMOVER');
INSERT INTO role(nome) VALUES('SALVAR');